CREATE TABLE public.store_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_no bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  recipient_name text NOT NULL,
  recipient_phone text NOT NULL,
  recipient_id_card text NOT NULL,
  recipient_address text NOT NULL,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_brl numeric NOT NULL DEFAULT 0,
  status recarga_status NOT NULL DEFAULT 'pending',
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE ON public.store_orders TO authenticated;
GRANT ALL ON public.store_orders TO service_role;

ALTER TABLE public.store_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "own orders select" ON public.store_orders FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'organizador'));
CREATE POLICY "own orders insert" ON public.store_orders FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());
CREATE POLICY "staff orders update" ON public.store_orders FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'organizador'))
  WITH CHECK (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'organizador'));

CREATE TRIGGER trg_store_orders_updated_at BEFORE UPDATE ON public.store_orders
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE OR REPLACE FUNCTION public.notify_admin_new_store_order()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  r record;
  v_id uuid;
  v_anon_key text := 'REEMPLAZA_CON_TU_ANON_KEY';
  v_url text := 'https://tudominio.com/api/public/push/dispatch';
BEGIN
  FOR r IN SELECT user_id FROM public.user_roles WHERE role = 'admin' LOOP
    INSERT INTO public.notifications (user_id, title, body)
    VALUES (r.user_id, 'Nuevo pedido VipShop',
      'Pedido #' || NEW.order_no || ' para ' || NEW.recipient_name || ' por R$ ' || NEW.total_brl || '.')
    RETURNING id INTO v_id;
    PERFORM net.http_post(
      url := v_url,
      headers := jsonb_build_object('Content-Type','application/json','apikey', v_anon_key),
      body := jsonb_build_object('notification_id', v_id));
  END LOOP;
  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION public.notify_admin_new_store_order() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER trg_notify_admin_new_store_order AFTER INSERT ON public.store_orders
  FOR EACH ROW EXECUTE FUNCTION public.notify_admin_new_store_order();

CREATE OR REPLACE FUNCTION public.notify_store_order_status_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_title text;
  v_body text;
  v_id uuid;
  v_anon_key text := 'REEMPLAZA_CON_TU_ANON_KEY';
  v_url text := 'https://tudominio.com/api/public/push/dispatch';
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF NEW.status = 'processing' THEN
      v_title := 'Pedido en proceso';
      v_body := 'Tu pedido VipShop #' || NEW.order_no || ' está siendo preparado.';
    ELSIF NEW.status = 'completed' THEN
      v_title := '¡Pedido entregado!';
      v_body := 'Tu pedido VipShop #' || NEW.order_no || ' fue entregado.';
    ELSIF NEW.status = 'rejected' THEN
      v_title := 'Pedido rechazado';
      v_body := 'Tu pedido VipShop #' || NEW.order_no || ' fue rechazado. Contáctanos.';
    ELSE
      RETURN NEW;
    END IF;
    INSERT INTO public.notifications (user_id, title, body)
    VALUES (NEW.user_id, v_title, v_body)
    RETURNING id INTO v_id;
    PERFORM net.http_post(
      url := v_url,
      headers := jsonb_build_object('Content-Type','application/json','apikey', v_anon_key),
      body := jsonb_build_object('notification_id', v_id));
  END IF;
  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION public.notify_store_order_status_change() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER trg_notify_store_order_status_change AFTER UPDATE ON public.store_orders
  FOR EACH ROW EXECUTE FUNCTION public.notify_store_order_status_change();